repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.3.1
    hooks:
      - id: pip-compile
        name: pip-compile production
        files: ^app/requirements/production\.(in|txt)$
        args: [--generate-hashes, app/requirements/production.in]
  - repo: https://github.com/psf/black
    rev: 21.11b1
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/timothycrosley/isort
    # isort config is in setup.cfg
    rev: 5.9.3
    hooks:
      - id: isort
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    # flake8 config is in setup.cfg
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3
