repos:
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.3.1
    hooks:
    hooks:
      - id: pip-compile
        name: pip-compile production
        files: ^backend/requirements/production\.(in|txt)$
        args: [--generate-hashes, backend/requirements/production.in]
      - id: pip-compile
        name: pip-compile develop
        files: ^backend/requirements/develop\.(in|txt)$
        args: [--generate-hashes, backend/requirements/develop.in]
